name: turnkey_api_key_stamper
description: A Dart package for API stamping functionalities.
version: 0.1.0
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  elliptic: ^0.3.11
  ecdsa: ^0.1.2
  turnkey_http: ^0.1.0
  turnkey_encoding: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  build_test: ^2.0.0
