name: turnkey_sdk_flutter
description: A complete SDK for building Flutter apps with Turnkey's packages
version: 1.2.0
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  turnkey_crypto: ^0.1.3
  turnkey_encoding: ^0.1.1
  turnkey_flutter_passkey_stamper: ^1.0.2
  turnkey_api_key_stamper: ^0.2.0
  turnkey_http: ^1.1.1
  app_links: ^6.3.3
  flutter_inappwebview: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
