name: turnkey_flutter_demo_app
description: A demo app using Turnkey's Flutter packages
publish_to: none
repository: https://github.com/tkhq/dart-sdk

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.1
  flutter_svg: ^1.0.3
  http: ^1.3.0
  turnkey_crypto: ^0.1.1
  turnkey_encoding: ^0.1.0
  turnkey_flutter_passkey_stamper: ^0.1.1
  turnkey_api_key_stamper: ^0.1.1
  turnkey_http: ^0.2.0
  turnkey_sdk_flutter:
    path: ../../packages/sdk-flutter
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  sign_in_with_apple: ^6.1.4
  intl_phone_number_input: ^0.7.4
  flutter_libphonenumber_ios: ^1.4.0
  flutter_inappwebview: ^6.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/google.svg
    - assets/images/apple.svg
    - .env
