name: turnkey_http
description: A Dart package for making HTTP requests to the Turnkey API.
version: 1.1.1
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.0.4
  http: ^1.3.0
  json_annotation: ^4.9.0
  turnkey_encoding: ^0.1.0
  turnkey_api_key_stamper: ^0.1.2+1
  swagger_dart_code_generator: ">=3.0.1 <5.0.0"
  path: ^1.9.0
  glob: ^2.1.0
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
