name: turnkey_flutter_passkey_stamper
description: A Flutter package for passkey stamping functionalities.
version: 0.1.0
repository: https://github.com/tkhq/dart-sdk
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  passkeys: ^2.4.0
  turnkey_http:
    path: ../http
  turnkey_encoding: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  build_test: ^2.0.0
