name: turnkey_flutter_passkey_stamper
description: A Flutter package for passkey stamping functionalities.
version: 1.0.1
repository: https://github.com/tkhq/dart-sdk

environment:
  sdk: ^3.6.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  passkeys: ^2.4.0
  turnkey_http: ^1.1.0
  turnkey_encoding: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  build_test: ^2.0.0